#!/usr/bin/env bash

set -eu
set -o pipefail

cd "$(dirname $0)/.."

if [ -f .env ]; then
  set -o allexport
  eval "$(cat .env | grep -v '^#')"
  set +o allexport
fi

migrate \
  -url "$APP_DATABASE_URL" \
  -path ./data/migrations \
  "$@"
