apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: torinos-api
  namespace: torinos-api
  annotations:
    kubernetes.io/ingress.global-static-ip-name: torinos-api
spec:
  tls:
    - secretName: tls
  backend:
    serviceName: torinos-api
    servicePort: 80
